[package]
name = "solana-discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "*"

[features]
test-bpf = []

[dev-dependencies]
assert_matches = "*"
solana-program-test = "*"
solana-sdk = "*"
solana-validator = "=*"

[lib]
crate-type = ["cdylib", "lib"]
